### ISSUE TITLE
Api documentation not found.

### ISSUE THREAD

**Issue by Duued** [dragdev-studios/yourapps.cyou#2]
![image](https://user-images.githubusercontent.com/66633587/108722503-3b8d7a00-74f1-11eb-8846-a88e5ed3472b.png)

**Comment by timedoutuk** [comment]
what am I meant to be looking at here? Please provide a description and examples on how to repro, etc.

**Comment by Duued** [comment]
If you go to yourapps.cyou, the api documentation  and open that, it says not found, like so.
